shared:
  adjectives:
    - abrupt
    - accurate
    - adamant
    - addicting
    - adorable
    - adventurous
    - aggressive
    - agreeable
    - alert
    - alleged
    - alive
    - alluring
    - amazing
    - amused
    - amusing
    - ancient
    - animated
    - angry
    - annoyed
    - annoying
    - anxious
    - ardent
    - aromatic
    - arrogant
    - aspiring
    - astonishing
    - attractive
    - average
    - auspicious
    - awesome
    - beautiful
    - best
    - better
    - bewildered
    - big
    - bitter
    - black
    - blazing
    - bloody
    - blue
    - blushing
    - bored
    - boundless
    - brainy
    - brass
    - brave
    - brawny
    - breakable
    - breezy
    - brief
    - bright
    - broad
    - burning
    - busy
    - cagey
    - callous
    - calm
    - capable
    - capricious
    - careful
    - careless
    - caring
    - cautious
    - celtic
    - certain
    - charming
    - cheerful
    - chief
    - chilly
    - classy
    - clean
    - clear
    - clever
    - cloudy
    - clumsy
    - coastal
    - cold
    - colorful
    - colossal
    - comfortable
    - common
    - complex
    - concerned
    - condemned
    - confused
    - cool
    - cooperative
    - copper
    - courageous
    - crazy
    - crooked
    - cruel
    - cuddly
    - curious
    - cute
    - dangerous
    - dapper
    - daring
    - dark
    - dashing
    - dazzled
    - dazzling
    - dear
    - decisive
    - deep
    - defiant
    - delicate
    - delightful
    - demonic
    - desert
    - detailed
    - determined
    - diamond
    - different
    - difficult
    - distinct
    - disturbed
    - dizzy
    - doubtful
    - drab
    - drifting
    - dull
    - dynamic
    - eager
    - early
    - easy
    - elated
    - electric
    - elegant
    - elfin
    - elite
    - eloquent
    - eminent
    - enchanting
    - encouraging
    - energetic
    - enthusiastic
    - envious
    - etched
    - eternal
    - ethereal
    - evil
    - excellent
    - excited
    - expensive
    - exuberant
    - exultant
    - fabulous
    - faded
    - faint
    - fair
    - faithful
    - familiar
    - famous
    - fancy
    - fantastic
    - far
    - fascinated
    - fast
    - fervent
    - festive
    - fierce
    - fiery
    - fine
    - first
    - flaming
    - flashy
    - flawless
    - flippant
    - floating
    - foolish
    - forever
    - forgotten
    - fortunate
    - fragile
    - frail
    - frantic
    - free
    - fresh
    - friendly
    - frightened
    - funny
    - fuzzy
    - gambling
    - gaudy
    - general
    - gentle
    - giant
    - giddy
    - gifted
    - gigantic
    - glamorous
    - gleaming
    - glib
    - glistening
    - glorious
    - glossy
    - good
    - goofy
    - gorgeous
    - graceful
    - grandiose
    - grateful
    - great
    - green
    - grumpy
    - gutsy
    - hallowed
    - handsome
    - handy
    - happy
    - healthy
    - heavenly
    - heavy
    - helpful
    - helpless
    - high
    - hilarious
    - hollow
    - hollywood
    - homeless
    - homely
    - honorable
    - horrible
    - hot
    - huge
    - humorous
    - hungry
    - hurt
    - hushed
    - hypnotic
    - icy
    - illustrious
    - igneous
    - imaginary
    - immense
    - imminent
    - impartial
    - imperfect
    - important
    - imported
    - impossible
    - incredible
    - inexpensive
    - innocent
    - inquisitive
    - intelligent
    - itchy
    - invincible
    - jaded
    - jagged
    - jazzy
    - jealous
    - jittery
    - jolly
    - joyous
    - keen
    - kind
    - known
    - languid
    - last
    - late
    - lavish
    - lazy
    - lean
    - learned
    - left
    - legal
    - legendary
    - lethal
    - level
    - light
    - like
    - lingering
    - little
    - lively
    - living
    - lonely
    - lonesome
    - long
    - longing
    - loose
    - lost
    - loud
    - lovely
    - low
    - lowly
    - lucky
    - lush
    - macaroni
    - magical
    - magnetic
    - magnificent
    - majestic
    - marked
    - marvelous
    - massive
    - material
    - mature
    - meek
    - melody
    - melodic
    - melted
    - mighty
    - minor
    - misty
    - mixed
    - modern
    - motionless
    - momentous
    - muddled
    - muddy
    - mushy
    - mute
    - mysterious
    - naive
    - narrow
    - nasty
    - naughty
    - near
    - neat
    - nervous
    - nice
    - noiseless
    - noisy
    - nonchalant
    - nonstop
    - normal
    - nosy
    - nutty
    - obedient
    - obnoxious
    - obsequious
    - odd
    - old
    - open
    - optimal
    - ordinary
    - outgoing
    - outrageous
    - outspoken
    - outstanding
    - overjoyed
    - overrated
    - pale
    - panicky
    - past
    - peaceful
    - perfect
    - petite
    - plain
    - pleasant
    - plucky
    - poised
    - polite
    - political
    - poor
    - possible
    - powerful
    - precious
    - premium
    - present
    - previous
    - prickly
    - private
    - proud
    - quaint
    - quick
    - quiet
    - quirky
    - ragged
    - rainy
    - rampant
    - rapid
    - rare
    - ready
    - real
    - rebel
    - regular
    - relieved
    - remarkable
    - rhythmic
    - rich
    - right
    - ripe
    - rough
    - round
    - royal
    - rustic
    - safe
    - same
    - savvy
    - scary
    - second
    - secret
    - secretive
    - sedate
    - selfish
    - separate
    - serene
    - serious
    - shallow
    - sharp
    - shiny
    - shocking
    - short
    - shrill
    - shy
    - silent
    - silky
    - silly
    - simple
    - skillful
    - sky
    - sleepy
    - slippery
    - slow
    - small
    - smart
    - smiling
    - smoggy
    - smooth
    - soft
    - solid
    - somber
    - sore
    - sour
    - southern
    - sparkling
    - special
    - spellbinding
    - spicy
    - splendid
    - spotless
    - standing
    - steadfast
    - steady
    - steep
    - stormy
    - strange
    - strong
    - stupid
    - subdued
    - successful
    - sudden
    - sunny
    - sunstruck
    - super
    - superb
    - supreme
    - sweet
    - swift
    - talented
    - tall
    - tame
    - tan
    - tangy
    - tasty
    - tart
    - telling
    - temporary
    - tender
    - tense
    - terrible
    - terrific
    - thankful
    - thick
    - thin
    - thoughtful
    - thoughtless
    - thundering
    - tidy
    - tiny
    - tired
    - tough
    - towering
    - troubled
    - troubling
    - true
    - typical
    - unequaled
    - unique
    - unknown
    - unruly
    - unsightly
    - unusual
    - upset
    - uptight
    - useful
    - vagabond
    - vague
    - valuable
    - various
    - vast
    - versed
    - victorious
    - vivacious
    - violent
    - volatile
    - voracious
    - waiting
    - wandering
    - warm
    - wary
    - wayward
    - weary
    - whimsical
    - white
    - wicked
    - wide
    - wild
    - willing
    - willful
    - windy
    - wiry
    - wise
    - wishful
    - wistful
    - witty
    - wonderful
    - wooden
    - worrisome
    - worrying
    - wrathful
    - wrong
    - wry
    - young
    - yummy
    - zany
    - zealous
  nouns:
    - ability
    - access
    - accident
    - account
    - act
    - action
    - activity
    - actor
    - ad
    - addition
    - address
    - advantage
    - advice
    - affair
    - afternoon
    - age
    - agency
    - agreement
    - air
    - alarm
    - ambition
    - amount
    - analysis
    - analyst
    - angel
    - angle
    - animal
    - answer
    - anxiety
    - appearance
    - apple
    - application
    - appointment
    - approval
    - arch
    - area
    - argument
    - army
    - arrival
    - arrow
    - art
    - article
    - attempt
    - attraction
    - aspect
    - assignment
    - assistance
    - assistant
    - association
    - assumption
    - atmosphere
    - attempt
    - attention
    - attitude
    - audience
    - aura
    - autumn
    - average
    - awareness
    - bad
    - badge
    - balance
    - ball
    - band
    - bank
    - base
    - basis
    - basket
    - bat
    - bath
    - battle
    - bead
    - beam
    - belief
    - bell
    - benefit
    - bird
    - bit
    - blade
    - blessing
    - blood
    - blush
    - board
    - boat
    - body
    - bonus
    - book
    - border
    - boss
    - bottom
    - box
    - boundary
    - branch
    - breath
    - brick
    - bubble
    - buyer
    - cake
    - camera
    - candle
    - candidate
    - cannon
    - capital
    - caption
    - car
    - card
    - care
    - career
    - case
    - cash
    - cat
    - category
    - cause
    - cave
    - celebration
    - cell
    - cent
    - chain
    - champion
    - chance
    - channel
    - chapter
    - charity
    - charm
    - cheek
    - cherry
    - chest
    - chocolate
    - choice
    - chum
    - circle
    - city
    - class
    - client
    - climate
    - clock
    - cloth
    - clothes
    - clover
    - coach
    - coast
    - coffee
    - coil
    - collection
    - combination
    - comfort
    - committee
    - communication
    - company
    - comparison
    - competition
    - complaint
    - concept
    - conclusion
    - condition
    - confusion
    - connection
    - consequence
    - construction
    - contact
    - context
    - contract
    - contribution
    - control
    - conversation
    - cookie
    - copper
    - copy
    - cord
    - country
    - county
    - courage
    - course
    - cousin
    - cover
    - craft
    - cream
    - credit
    - criticism
    - crown
    - crusade
    - culture
    - currency
    - customer
    - cycle
    - darkness
    - dart
    - data
    - date
    - day
    - daze
    - dealer
    - death
    - debt
    - decision
    - deer
    - definition
    - degree
    - delivery
    - demand
    - demon
    - department
    - departure
    - depth
    - description
    - design
    - desire
    - detail
    - development
    - device
    - devil
    - diamond
    - difference
    - difficulty
    - direction
    - director
    - dirt
    - disaster
    - discipline
    - discussion
    - disk
    - distribution
    - doll
    - dragon
    - drama
    - drawing
    - driver
    - drum
    - dust
    - earth
    - ease
    - east
    - economy
    - edge
    - editor
    - education
    - effect
    - effort
    - egg
    - election
    - ember
    - emotion
    - emphasis
    - employee
    - employer
    - end
    - energy
    - engine
    - enthusiasm
    - entry
    - environment
    - error
    - estate
    - event
    - exam
    - example
    - exchange
    - excitement
    - exercise
    - experience
    - explanation
    - expression
    - extent
    - eye
    - face
    - fact
    - fall
    - family
    - fan
    - farmer
    - feather
    - feature
    - feedback
    - feeling
    - field
    - fiesta
    - fight
    - figure
    - film
    - finding
    - fire
    - fish
    - fizz
    - flag
    - flame
    - flavor
    - flight
    - flower
    - fly
    - focus
    - fog
    - food
    - force
    - form
    - fortune
    - foundation
    - fox
    - frame
    - freedom
    - friend
    - frog
    - frost
    - fuel
    - fun
    - future
    - galaxy
    - game
    - garden
    - gate
    - gene
    - ghost
    - gift
    - glory
    - goal
    - gold
    - ground
    - group
    - growth
    - guidance
    - guide
    - half
    - hall
    - hand
    - harmony
    - hat
    - head
    - heart
    - heat
    - height
    - heir
    - hillside
    - highway
    - history
    - holiday
    - home
    - honey
    - honor
    - hope
    - hotel
    - hour
    - house
    - ice
    - idea
    - idol
    - illusion
    - image
    - imagination
    - impact
    - importance
    - impression
    - improvement
    - impulse
    - income
    - independence
    - indication
    - industry
    - information
    - initiative
    - injury
    - ink
    - inside
    - inspection
    - inspector
    - instance
    - instruction
    - intention
    - interaction
    - interest
    - introduction
    - invention
    - investment
    - iris
    - island
    - issue
    - item
    - jewel
    - job
    - joke
    - journey
    - judgement
    - jumper
    - key
    - kitten
    - knowledge
    - lab
    - lace
    - ladder
    - lake
    - lamp
    - land
    - laugh
    - law
    - lawyer
    - lead
    - leader
    - leaf
    - length
    - level
    - letter
    - leopard
    - level
    - library
    - life
    - light
    - limit
    - line
    - linen
    - link
    - lion
    - list
    - literature
    - location
    - lock
    - locket
    - look
    - loss
    - lyre
    - machine
    - magic
    - mail
    - manager
    - map
    - market
    - marble
    - mark
    - mask
    - match
    - material
    - matter
    - meal
    - meaning
    - measure
    - media
    - medicine
    - medium
    - member
    - memory
    - menu
    - message
    - metal
    - method
    - midnight
    - mind
    - mine
    - mint
    - minute
    - mist
    - mixture
    - mode
    - model
    - moment
    - money
    - month
    - mood
    - moon
    - moonbeam
    - morning
    - motion
    - mouse
    - mountain
    - move
    - mud
    - music
    - myth
    - name
    - nation
    - nature
    - negotiation
    - network
    - news
    - night
    - noise
    - north
    - note
    - nothing
    - number
    - object
    - obligation
    - ocean
    - offer
    - office
    - oil
    - operation
    - opinion
    - opportunity
    - orange
    - order
    - organization
    - ornament
    - outcome
    - outside
    - owl
    - owner
    - page
    - paint
    - painting
    - paper
    - park
    - partner
    - part
    - party
    - passenger
    - passion
    - patience
    - payment
    - penalty
    - peace
    - performance
    - period
    - permission
    - personality
    - perspective
    - pet
    - philosophy
    - phoenix
    - photo
    - piano
    - picture
    - pie
    - piece
    - pilot
    - pirate
    - pizza
    - place
    - plan
    - platform
    - player
    - pleasure
    - pocket
    - poem
    - poet
    - poetry
    - point
    - policy
    - politics
    - position
    - possession
    - possibility
    - post
    - pot
    - potato
    - power
    - practice
    - preference
    - preparation
    - presence
    - presentation
    - pressure
    - price
    - priority
    - problem
    - procedure
    - process
    - prodigy
    - product
    - profession
    - professor
    - profit
    - program
    - promotion
    - property
    - proposal
    - protection
    - protest
    - purpose
    - quality
    - quantity
    - quarter
    - quartz
    - question
    - radio
    - rail
    - rain
    - rainfall
    - rainstorm
    - rake
    - range
    - rate
    - ratio
    - reaction
    - reality
    - reason
    - rebellion
    - reception
    - recipe
    - recognition
    - recommendation
    - record
    - recording
    - reflection
    - region
    - regret
    - relation
    - relationship
    - replacement
    - republic
    - reputation
    - request
    - requirement
    - research
    - resolution
    - resource
    - response
    - responsibility
    - rest
    - result
    - revenue
    - review
    - revolution
    - reward
    - riddle
    - ring
    - risk
    - river
    - road
    - robin
    - rock
    - rocket
    - role
    - room
    - rule
    - rush
    - salt
    - sample
    - sand
    - scale
    - scene
    - scent
    - science
    - screen
    - sea
    - section
    - sector
    - seed
    - selection
    - sense
    - series
    - service
    - session
    - setting
    - shade
    - shape
    - share
    - shimmer
    - ship
    - shore
    - show
    - side
    - sight
    - sign
    - signature
    - significance
    - silk
    - silver
    - singer
    - site
    - situation
    - size
    - skill
    - sky
    - skyline
    - sleet
    - snow
    - snowbank
    - snowdrift
    - society
    - soil
    - solution
    - song
    - sorbet
    - sound
    - soup
    - source
    - south
    - space
    - spark
    - speaker
    - speech
    - spell
    - spring
    - sport
    - spy
    - square
    - stage
    - stamp
    - standard
    - star
    - state
    - statement
    - station
    - steed
    - step
    - stock
    - storage
    - store
    - story
    - stranger
    - strategy
    - stream
    - stress
    - structure
    - student
    - studio
    - study
    - style
    - subject
    - success
    - sugar
    - suggestion
    - summer
    - sun
    - sunlight
    - sunshine
    - surprise
    - swing
    - swirl
    - sympathy
    - system
    - table
    - tale
    - task
    - tax
    - tea
    - teacher
    - technology
    - temper
    - temperature
    - templar
    - tension
    - term
    - test
    - texture
    - theory
    - thing
    - thought
    - thread
    - thrill
    - throne
    - thunder
    - thunderstorm
    - ticket
    - tiger
    - time
    - title
    - tongue
    - tool
    - tooth
    - top
    - topic
    - touch
    - town
    - toy
    - trade
    - tradition
    - trail
    - train
    - trainer
    - training
    - tree
    - trick
    - trip
    - truth
    - turn
    - twist
    - two
    - type
    - understanding
    - union
    - unit
    - university
    - value
    - variation
    - variety
    - vase
    - vehicle
    - veil
    - vein
    - verse
    - version
    - vessel
    - victory
    - video
    - view
    - village
    - virus
    - visitor
    - voice
    - volume
    - voyage
    - voyager
    - wall
    - war
    - warning
    - watch
    - water
    - wave
    - way
    - weakness
    - wealth
    - weather
    - web
    - week
    - west
    - wheel
    - while
    - whistle
    - wind
    - wine
    - wing
    - winner
    - winter
    - wire
    - wish
    - wisp
    - wood
    - word
    - work
    - worker
    - world
    - wren
    - writer
    - writing
    - year
    - youth
    - zeal
    - zen
    - zenith
    - zephyr
    - zest
    - zillion
    - zinc
    - zing
    - zither
    - zone
    - zoo
