shared:
  modes:
    - light
    - dark
  light_themes:
    - light
    - cupcake
    - bumblebee
    - emerald
    - corporate
    - retro
    - cyberpunk
    - valentine
    - garden
    - lofi
    - pastel
    - fantasy
    - wireframe
    - autumn
    - acid
    - lemonade
    - winter
    - nord
    - caramellatte
    - silk
  dark_themes:
    - dark
    - synthwave
    - halloween
    - forest
    - aqua
    - black
    - luxury
    - dracula
    - business
    - acid
    - night
    - coffee
    - dim
    - sunset
    - abyss
