default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: [ critical, mailers, notifications, default, low_priority ]
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

development:
  <<: *default
  workers:
    - queues: [ critical, mailers, notifications, default, low_priority ]
      threads: <%= ENV.fetch("JOB_THREADS", 1) %>
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 0.1

test:
  <<: *default

production:
  <<: *default
  workers:
    - queues: critical
      threads: 10
      processes: 1  # 10 workers
      polling_interval: 0.1

    - queues: [default, solid_queue_recurring, mailers, notifications, low_priority]
      threads: 5
      processes: 1  # 5 workers
      polling_interval: 5
