# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  migrate_legacy_horses:
    class: UpdateLegacyHorsesJob
    queue: low_priority
    schedule: every 2 minutes
  auto_create_monthly_auction:
    class: CreateMonthlyAuctionJob
    queue: low_priority
    schedule: 1 0 1 * * # first day of every month
  auto_create_two_year_old_auction:
    class: CreateTwoYearOldAuctionJob
    queue: low_priority
    schedule: 9 0 1 2 * # first day of Feb
  auto_create_mixed_auction:
    class: CreateMixedAuctionJob
    queue: low_priority
    schedule: 9 0 1 6 * # first day of June
  auto_create_select_auction:
    class: CreateSelectAuctionJob
    queue: low_priority
    schedule: 9 0 1 8 * # first day of August
  auto_create_foal_auction:
    class: CreateFoalAuctionJob
    queue: low_priority
    schedule: 9 0 1 11 * # first day of November
  delete_empty_auctions:
    class: DeleteEmptyAuctionsJob
    queue: low_priority
    schedule: at 11:45pm every day
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
