# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  daily_update:
    class: Daily::MorningUpdatesJob
    queue: default
    schedule: 2 0 * * *
  horse_legacy_migrate:
    class: UpdateLegacyHorsesJob
    queue: low_priority
    schedule: every 30 minutes
  auction_create_monthly_auction:
    class: Auctions::CreateMonthlyAuctionJob
    queue: low_priority
    schedule: 1 0 1 1,3,4,5,7,9,10,12 * # first day of every month that does not have another auction
  auction_create_two_year_old:
    class: Auctions::CreateTwoYearOldAuctionJob
    queue: low_priority
    schedule: 9 0 1 2 * # first day of Feb
  auction_create_mixed:
    class: Auctions::CreateMixedAuctionJob
    queue: low_priority
    schedule: 9 0 1 6 * # first day of June
  auction_create_select:
    class: Auctions::CreateSelectAuctionJob
    queue: low_priority
    schedule: 9 0 1 8 * # first day of August
  auction_create_foal:
    class: Auctions::CreateFoalAuctionJob
    queue: low_priority
    schedule: 9 0 1 11 * # first day of November
  auction_delete_empty:
    class: Daily::DeleteEmptyAuctionsJob
    queue: low_priority
    schedule: at 11:45pm every day
  auction_sales_scheduling:
    class: Auctions::ScheduleSalesJob
    queue: default
    schedule: 3 */6 * * * # at minute 3 past every 6th hour
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
