on:
  workflow_call:
    secrets:
      lcov-token:
        description: 'Github token for ff-bot'
        required: true
      code-climate-token:
        description: 'API key to report to Code Climate'
        required: true
      cypress-record-key:
        description: 'API key to report to Cypress Cloud'
        required: true

env:
  CI: true
  EXTERNAL_CI: true
  RAILS_ENV: test
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/final_furlong_test
  CACHE_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/final_furlong_test_cache
  QUEUE_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/final_furlong_test_queue
  REDIS_URL: redis://localhost:6379/0
  COVERAGE: true
  MAILTRAP_API_KEY: foo

jobs:
  tests:
    name: Tests
    timeout-minutes: 20
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
        image: mysql:latest
        env:
          MYSQL_USER: developer
          MYSQL_DATABASE: final_furlong_legacy_test
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: mysql
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      redis:
        image: redis
        ports: [ '6379:6379' ]
        options: --entrypoint redis-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Yarn Cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: yarn-cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn Install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --prefer-offline

      - name: Install libvips
        run: |
          sudo apt-get update
          sudo apt-get -y install libvips

      - name: Set up primary database
        run: |
          cp config/database.yml.github_actions config/database.yml
          bin/rails db:create:primary db:schema:load:primary

      - name: Set up queue database
        run: |
          cp config/database.yml.github_actions config/database.yml
          bin/rails db:create:queue db:schema:load:queue

      - name: Set up cache database
        run: |
          cp config/database.yml.github_actions config/database.yml
          bin/rails db:create:cache db:schema:load:cache

      - name: Set up legacy database
        run: |
          cp config/database.yml.github_actions config/database.yml
          bin/rails db:create:legacy db:schema:load:legacy

      - name: CI Run
        run: |
          bin/ci

      - name: Publish Coverage
        uses: paambaati/codeclimate-action@v5.0.0
        continue-on-error: true
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.code-climate-token }}
        with:
          coverageLocations: |
            ${{github.workspace}}/*.xml:simplecov
            ${{github.workspace}}/*.lcov:lcov

      - name: Coverage Report
        if: github.event.pull_request
        uses: ewjoachim/coverage-comment-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERAGE_FILE: "coverage/coverage.xml"

      - name: Code Coverage Summary Report
        if: github.event.pull_request
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          filename: coverage/coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '38 66'
