on:
  workflow_call:

env:
  CI: true

jobs:
  linters:
    name: Linters
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Yarn install
        run: yarn --prefer-offline

      - name: RuboCop
        run: |
          bundle exec rubocop

      - name: HamlLint
        run: |
          HAML_LINT_RUBOCOP_CONF=.rubocop_haml.yml bundle exec haml-lint

      - name: Fasterer
        run: |
          bin/fasterer

      - name: EsLint
        run: |
          yarn run eslint app/javascript

      - name: StyleLint
        run: |
          yarn run stylelint app/assets/stylesheets

      - name: Locales
        run: |
          bin/i18n-tasks health
