on:
  workflow_call:

env:
  CI: true

jobs:
  linters:
    name: Linters
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Yarn install
        run: yarn --prefer-offline

      - name: RuboCop
        run: |
          bundle exec rubocop

      - name: Set up primary database
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/final_furlong_test"
        run: |
          cp config/database.yml.github_actions config/database.yml
          bin/rails db:create:primary db:schema:load:primary

      - name: Set up legacy database
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/final_furlong_test"
        run: |
          cp config/database.yml.github_actions config/database.yml
          bin/rails db:create:legacy db:schema:load:legacy

      - name: Active Record Doctor
        run: |
          bundle exec rails active_record_doctor

      - name: HamlLint
        run: |
          bundle exec haml-lint

      - name: Fasterer
        run: |
          bin/fasterer

      - name: EsLint
        run: |
          yarn run eslint app/javascript

      - name: StyleLint
        run: |
          yarn run stylelint app/assets/stylesheets
