on:
  workflow_call:

env:
  CI: true
  MAILTRAP_API_KEY: foo

jobs:
  security:
    name: Security
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Yarn Cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: yarn-cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Yarn Install
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --prefer-offline

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Security Checks
        run: |
          sh .github/scripts/security.sh
