on:
  workflow_call:
    secrets:
      lcov-token:
        description: 'Github token for ff-bot'
        required: true
      code-climate-token:
        description: 'API key to report to Code Climate'
        required: true

env:
  CI: true
  RAILS_ENV: test
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/final_furlong_test
  REDIS_URL: redis://localhost:6379/0
  COVERAGE: true

jobs:
  tests:
    name: Tests
    timeout-minutes: 20
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: [ "5432:5432" ]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mysql:
        image: mysql:latest
        env:
          MYSQL_USER: developer
          MYSQL_DATABASE: final_furlong_legacy_test
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: mysql
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      redis:
        image: redis
        ports: [ '6379:6379' ]
        options: --entrypoint redis-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Set up primary database
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/final_furlong_test"
        run: |
          cp config/database.yml.github_actions config/database.yml
          bin/rails db:create:primary db:schema:load:primary

      - name: Set up legacy database
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/final_furlong_test"
        run: |
          cp config/database.yml.github_actions config/database.yml
          bin/rails db:create:legacy db:schema:load:legacy

      - name: Precompile Assets
        run: bin/rails assets:precompile

      - name: RSpec (Unit)
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/final_furlong_test"
        run: bin/rspec --tag ~type:system

      - name: RSpec (System)
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/final_furlong_test"
        run: bin/rspec --tag type:system

      - name: Combine Code Coverage
        env:
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/final_furlong_test"
        run: bin/rails coverage:report

      - name: Publish Coverage
        uses: paambaati/codeclimate-action@v3.0.0
        continue-on-error: true
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.code-climate-token }}
        with:
          coverageLocations: |
            ${{github.workspace}}/*.xml:simplecov
            ${{github.workspace}}/*.lcov:lcov

      - name: Coverage Report
        uses: ewjoachim/coverage-comment-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERAGE_FILE: "coverage/coverage.xml"

      - name: Code Coverage Summary Report
        if: github.event.pull_request
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          filename: coverage/coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Cobertura Coverage Report (Unit)
        uses: 5monkeys/cobertura-action@master
        with:
          path: coverage_unit/coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 42

      - name: Cobertura Coverage Report (Feature)
        uses: 5monkeys/cobertura-action@master
        with:
          path: coverage_feature/coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 47
