on:
  workflow_call:
    secrets:
      lcov-token:
        description: 'Github token for ff-bot'
        required: true
      code-climate-token:
        description: 'API key to report to Code Climate'
        required: true

env:
  CI: true
  RAILS_ENV: test
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/final_furlong_test
  REDIS_URL: redis://localhost:6379/0
  COVERAGE: true

jobs:
  tests:
    name: Tests
    timeout-minutes: 20
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup test database
        run: |
          cp config/database.yml.github_actions config/database.yml
          bin/rails db:create
          bin/rails db:test:prepare

      - name: Set up primary database
        env:
          POSTGRES_DB: final_furlong_test
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/final_furlong_test"
        run: |
          cp config/database.yml.github_actions config/database.yml
          bin/rails db:create:primary db:migrate:primary
      - name: Set up legacy database
        env:
          POSTGRES_DB: final_furlong_legacy_test
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/final_furlong_legacy_test"
        run: |
          cp config/database.yml.github_actions config/database.yml
          bin/rails db:create:legacy db:migrate:legacy

      - name: Test & Publish Coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.code-climate-token }}
        with:
          coverageCommand: bin/rspec

      - name: Coverage Report
        uses: ewjoachim/coverage-comment-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERAGE_FILE: "coverage/coverage.xml"

      - name: Code Coverage Summary Report
        if: github.event.pull_request
        uses: irongut/CodeCoverageSummary@v1.2.0
        with:
          filename: coverage/coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: false
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Cobertura Coverage Report
        uses: 5monkeys/cobertura-action@master
        with:
          path: coverage/coverage.xml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          minimum_coverage: 85
